import { type NextPage } from "next"
import Head from "next/head"
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs"

import { api } from "~/utils/api"

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" })
  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#4d435b] to-[#191a29] text-white">
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
      </main>
    </>
  )
}

export default Home
